name: Bug report
description: "Create a report to help us improve Mojo Launcher"
title: "[BUG] <Short description>"
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: >
        A clear and concise description of what the bug is.
      placeholder: >
        Example: I have to press CTRL for keyboard keys to work on my Keychron K2 keyboard when connected via Bluetooth.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs, Screenshots, or Videos
      description: |
        Please attach your `latestlog.txt` file, which is located in one of the following paths:

        - `/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files` (Android 10+)
        - `/storage/emulated/0/games/PojavLauncher/` (Android 9 or lower)

        Make sure hidden files are visible in your file manager. Recommended file explorers are **ZArchiver** or **MiXplorer**.

        You can also drag and drop screenshots or video recordings here.

        ⚠️ Don't click away while uploading — let it finish first.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: What steps should we follow to reproduce the issue?
      placeholder: |
        1. Open Mojo Launcher
        2. Start Minecraft Java
        3. Connect Bluetooth keyboard
        4. Keys only work when holding CTRL
      render: markdown
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen instead?
      placeholder: >
        Example: I expected my keyboard to work without holding CTRL.
    validations:
      required: true

  - type: textarea
    id: platform
    attributes:
      label: Device and Platform Info
      description: |
        Please provide your full device and version details.

        Example:
          - **Device model**: POCO X3 Pro
          - **CPU architecture**: arm64-v8a
          - **Android version**: 13
          - **Mojo Launcher version**: alpha-20250714-dbg
      value: |
          - Device model: 
          - CPU architecture: 
          - Android version: 
          - Mojo Launcher version: 
      render: markdown
    validations:
      required: true

  - type: textarea
    id: extras
    attributes:
      label: Anything else?
      description: |
        Any other context, logs, debug commands, or side effects you noticed?
    validations:
      required: false
